# to apply this, execute 'cat cli_utils.yaml | sed "s|HOME_SUB|$HOME|" | kubectl apply -f -'

---

apiVersion: v1
kind: Namespace
metadata:
  name: cli-utils

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli-utils-deployment
  namespace: cli-utils
  labels:
    app: cli-utils
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cli-utils
  template:
    metadata:
      labels:
        app: cli-utils
    spec:
      containers:
        - name: aws-cli
          image: ops/awscli:latest
          command: [ "/bin/sh", "-c" ]
          args: [ "trap : TERM INT; (while true; do sleep 86400; done) & wait" ]
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: /root/.aws
              name: aws-conf
              readOnly: true
          resources:
            requests:
              memory: "16Mi"
              cpu: "8m"
            limits:
              memory: "512Mi"
              cpu: "1"
        - name: k8s-cli
          image: ops/k8scli:latest
          command: [ "/bin/sh", "-c" ]
          args: [ "trap : TERM INT; (while true; do sleep 86400; done) & wait" ]
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: /root/.kube
              name: k8s-conf
              readOnly: true
          resources:
            requests:
              memory: "16Mi"
              cpu: "8m"
            limits:
              memory: "512Mi"
              cpu: "1"
      volumes:
        - name: aws-conf
          hostPath:
            path: HOME_SUB/.aws
        - name: k8s-conf
          hostPath:
            path: HOME_SUB/.kube
