# to apply this, execute 'kubectl apply -f cli_utils.yaml'

---

apiVersion: v1
kind: Namespace
metadata:
  name: cli-utils

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli-utils-deployment
  namespace: cli-utils
  labels:
    app: cli-utils
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cli-utils
  template:
    metadata:
      labels:
        app: cli-utils
    spec:
      containers:
        - name: aws-cli
          image: ops/awscli:latest
          command: [ "/bin/sh", "-c" ]
          args: [ "trap : TERM INT; (while true; do sleep 1000; done) & wait" ]
          imagePullPolicy: Never
