---
version: '3.7'

services:
  ansible:
    build:
      args:
        ANSIBLE_RELEASE: '2.8.5'
        BASE_VERSION: '3-alpine'
      context: .
      dockerfile: Dockerfile.ansible
    image: ops/ansible:latest
    volumes:
      - $PWD:/app
    working_dir: /app
    entrypoint: ['ansible']

  aws:
    build:
      args:
        BASE_VERSION: '3-alpine'
      context: .
      dockerfile: Dockerfile.aws
    image: ops/awscli:latest
    volumes:
      - $HOME/.aws:/root/.aws:ro
      - $PWD:/app
    working_dir: /app
    entrypoint: ['aws']

  kubectl:
    build:
      args:
        BASE_VERSION: '3.10'
        K8S_RELEASE: 'v1.16.2'
      context: .
      dockerfile: Dockerfile.k8s
    environment:
      - KUBECONFIG=/root/.kube/config
    image: ops/k8scli:latest
    volumes:
      - $HOME/.kube:/root/.kube:ro
      - $PWD:/app
    working_dir: /app
    entrypoint: ['/kubectl']

  terraform:
    image: hashicorp/terraform:0.12.12
    volumes:
      - $PWD:/app
    working_dir: /app
    entrypoint: ['terraform']
