#!/usr/bin/env bash

# https://ghost.org/changelog/prevent-master-push/
protected_branches=('main' 'master')
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [[ "${protected_branches[*]}" =~ "${current_branch}" ]]
then
    read -p "You're about to push '${current_branch}' directly, is that what you intended? [y|n] " -n 1 -r < /dev/tty
    echo
    if echo $REPLY | grep -E '^[Yy]$' > /dev/null
    then
        exit 0 # push will execute
    fi
    exit 1 # push will not execute
else
    exit 0 # push will execute
fi
